Tests that pause on exception in internal script does not crash.
